name: publish 

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  Github_ID: ${{ github.run_id }}
jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: Bump version and push tag
      uses: kimgault/github-tag-action@v1.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: master
        BUMP: major
    - name: Print new build number
      run: echo GITHUB_TOKEN
