name: publish 

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  Github_ID: ${{ github.run_id }}
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Generate build number
      uses: einaregilsson/build-number@v3
      with:
        token: ${{secrets.github_token}}        
    - name: Print new build number
      run: echo ${{ github.event.release.tag_name }}.
      # Or, if you're on Windows: echo "Build number is ${env:BUILD_NUMBER}"}
