name: publish 

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  Github_ID: ${{ github.run_id }}
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Output Run ID
        run: echo ${{ github.run_id }}
      - name: Output Run Number
        run: echo ${{ github.run_number }}

      - name: Output Run ID
        run: echo ${{ env.Github_ID }}
