name: publish 

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  Github_ID: ${{ github.run_id }}
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Increment Step Major
        id: increment-semver-major
        uses: Benbentwo/increment-semver@master
        with:
          version-level: '-M'

      # Use the output from the `Increment Step X` step
      - name: Get the output version
        run: |
          echo "The new Major version was ${{ steps.increment-semver-major.outputs.version }}"
